### ISSUE TITLE
(c) custom ligature applied in 501(c)(3) is wrong

### ISSUE THREAD

**Issue by smagdali** [sharanda/manrope#81]
I am by no means an expert on fonts, so forgive any errors. The org I work for loves and uses manrope a lot but we have a problem...

"501(c)(3)" is a widely used[ official designation for a non-profit organisation in the US](https://en.wikipedia.org/wiki/501(c)(3)_organization): -  Manrope substitutes the copyright symbol for (c) in the middle of this [widely-used label](https://www.google.com/search?q=%22501%28c%29%283%29%22&client=safari). 

501©(3) - this is just plain wrong.

Is it possible to make the font only apply the custom ligature only when (c) is preceded by whitespace, rather than in the middle of a character string? This is the behaviour that the Gdocs and MS Word apply and it's much less likely to create a false positive. There's no use case for the copyright symbol in the middle of a word, that I can think of...

**Comment by sharanda** [comment]
@smagdali there are few options you can try:
- disable 'liga' font ligature settings https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings
- use Cyrillic /с to prevent specifically this custom alternative from working
- download trial version of Glyphs font software https://glyphsapp.com/ and Manrope source file https://github.com/sharanda/manrope/blob/master/sources/Manrope.glyphs
then delete parenleft_c_parenright.liga glyph, then export again.

hope it helps

**Comment by smagdali** [comment]
Deleted the glyph ok as per instructions, and exported - but struggling to rebuild. possibly unrelated.

```
stefan@MacBook-Pro manrope % make build
. venv/bin/activate; gftools builder sources/config.yaml && touch build.stamp
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:fontmake.font_project:Building variable font ../fonts/variable/Manrope-VF.ttf
ERROR:cu2qu.ufo:Glyphs named 'divide' have different number of segments
Traceback (most recent call last):
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/fontmake/font_project.py", line 968, in run_from_designspace
    self._run_from_designspace_interpolatable(
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/fontmake/font_project.py", line 1048, in _run_from_designspace_interpolatable
    self.build_variable_font(
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/fontmake/font_project.py", line 339, in build_variable_font
    font = ufo2ft.compileVariableTTF(
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/ufo2ft/__init__.py", line 540, in compileVariableTTF
    ttfDesignSpace = compileInterpolatableTTFsFromDS(
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/ufo2ft/__init__.py", line 374, in compileInterpolatableTTFsFromDS
    for source, ttf in zip(result.sources, ttfs):
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/ufo2ft/__init__.py", line 286, in compileInterpolatableTTFs
    glyphSets = call_preprocessor(ufos, **kwargs)
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/ufo2ft/__init__.py", line 61, in call_preprocessor
    return preProcessor.process()
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/ufo2ft/preProcessor.py", line 289, in process
    fonts_to_quadratic(
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/cu2qu/ufo.py", line 295, in fonts_to_quadratic
    raise IncompatibleFontsError(glyph_errors)
cu2qu.errors.IncompatibleFontsError: fonts contains incompatible glyphs: 'divide'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stefan/GitHub/manrope/venv/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/gftools/builder/__init__.py", line 183, in build
    self.build_variable()
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/gftools/builder/__init__.py", line 283, in build_variable
    output_files = self.run_fontmake(source, args)
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/gftools/builder/__init__.py", line 320, in run_fontmake
    FontProject().run_from_glyphs(source, **args)
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/fontmake/font_project.py", line 719, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/stefan/GitHub/manrope/venv/lib/python3.9/site-packages/fontmake/font_project.py", line 982, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'Manrope.glyphs' -> 'master_ufo/Manrope.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'divide'
make: *** [build.stamp] Error 1

```

**Comment by sharanda** [comment]
Glad it helped. The build error is related to Google fonts.

**Comment by smagdali** [comment]
Would you consider fixing this in master? Most of my colleagues use the font daily in Google Workspace so I'd like to help get it fixed there (I'm guessing  this means updating at Google Fonts).
I don't think the workarounds you've proposed are practical for non-technical people using the font everyday... I'm guessing that the Cyrillic substitution option breaks search?
